stages:
  - build
  - deploy

# Build stage
build:
  stage: build
  tags:
    - ec2runner  # Match the tag assigned to your runner
  script:
    - docker-compose build  # Build Docker images

# Deploy stage
deploy:
  stage: deploy
  tags:
    - ec2runner  # Match the tag assigned to your runner
  script:
    - docker-compose down  # Stop existing containers
    - docker-compose up -d  # Deploy new containers
